spring.application.name=backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/topik_system
spring.datasource.username=postgres
spring.datasource.password=21102004

spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# ===============================
# JWT
# ===============================
jwt.secret=super-secret-key-123456
jwt.expiration=900000

# ===============================
# EMAIL (SMTP - Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tiena12004leloi@gmail.com
spring.mail.password=tlqiwlidxvmynaqf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# OAUTH2 GOOGLE
# ===============================
spring.security.oauth2.client.registration.google.client-id=363312805658-asgpjs3jlc51e24fgqhl0958nr6nm9sn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG

app.oauth2.redirect-url=http://localhost:3000/oauth2-success